### ISSUE TITLE
Causes LOVE to quit on Error

### ISSUE THREAD

**Issue by davisdude** [Shell64/GunigineAudio#2]
When the module is required (`love.audio = require 'GunigineAudio'`) this causes LOVE to not catch errors and instead fail on error, quitting.

```Lua
love.audio = require 'GunigineAudio'
error( 'Nothing appears' )
```

When you __just__ require it (`require 'GunigineAudio'`), no errors occur in the erroring.

**Comment by Shell64** [comment]
Can you try my lastest commit? Also, when trying to remove a source, instead of doing Source=nil do Source:destroy() before.

**Comment by davisdude** [comment]
I tried the latest commit, but LOVE still quits on error.
I have reproduced it down to the minimal case.

[Here's](https://www.dropbox.com/s/q48lavmhb01v0xy/Error.love?dl=1) the .love
[This](http://pastebin.com/VmitdhEp) is the main.lua

When I run the execute the files, whenever there is an error LOVE will quit and not display the error.

**Comment by Shell64** [comment]
Hello, the lastest commit works for me. I think you aren't using the lastest. Try this one: [link][link]
[link]:https://dl.dropboxusercontent.com/u/70131373/GunigineAudio-master.love

**Comment by davisdude** [comment]
Huh, that's weird. Works now, thanks. I must have downloaded the wrong version or something.
Thanks
